### ISSUE TITLE
Error: Solidity Compilation Error

### ISSUE THREAD

**Issue by Adarsh-gif-crypt** [petrosDemetrakopoulos/ethairballoons#17]
I tried using the library but it gave me this error

`Error: Solidity compilation error 
[{"component":"general","errorCode":"6651","formattedMessage":"TypeError: Data location must be \"storage\", \"memory\" or \"calldata\" for parameter in function, but none was given.\n  --> HealthContract.sol:21:20:\n   |\n21 | \tfunction isRecord(string recordAddress) internal view returns (bool isRec) {\n   | \t                  ^^^^^^^^^^^^^^^^^^^^\n\n","message":"Data location must be \"storage\", \"memory\" or \"calldata\" for parameter in function, but none was given.","severity":"error","sourceLocation":{"end":501,"file":"HealthContract.sol","start":481},"type":"TypeError"},{"component":"general","errorCode":"6651","formattedMessage":"TypeError: Data location must be \"memory\" or \"calldata\" for parameter in external function, but none was given.\n  --> HealthContract.sol:30:44:\n   |\n30 | \tfunction addRecord(string memory payload, string ID) external returns (bool success) {\n   | \t                                          ^^^^^^^^^\n\n","message":"Data location must be \"memory\" or \"calldata\" for parameter in external function, but none was given.","severity":"error","sourceLocation":{"end":814,"file":"HealthContract.sol","start":805},"type":"TypeError"},{"component":"general","errorCode":"6651","formattedMessage":"TypeError: Data location must be \"memory\" or \"calldata\" for parameter in external function, but none was given.\n  --> HealthContract.sol:39:21:\n   |\n39 | \tfunction getRecord(string id) external view returns (string memory payload){\n   | \t                   ^^^^^^^^^\n\n","message":"Data location must be \"memory\" or \"calldata\" for parameter in external function, but none was given.","severity":"error","sourceLocation":{"end":1091,"file":"HealthContract.sol","start":1082},"type":"TypeError"},{"component":"general","errorCode":"6651","formattedMessage":"TypeError: Data location must be \"memory\" or \"calldata\" for parameter in external function, but none was given.\n  --> HealthContract.sol:44:24:\n   |\n44 | \tfunction updateRecord(string id, string memory payload) external returns (bool success){\n   | \t
  ^^^^^^^^^\n\n","message":"Data location must be \"memory\" or \"calldata\" for parameter in external function, but none was given.","severity":"error","sourceLocation":{"end":1272,"file":"HealthContract.sol","start":1263},"type":"TypeError"},{"component":"general","errorCode":"6651","formattedMessage":"TypeError: Data location must be \"memory\" or \"calldata\" for parameter in external function, but none was given.\n  --> HealthContract.sol:59:24:\n   |\n59 | \tfunction deleteRecord(string id) external returns (bool success) {\n   | \t                      ^^^^^^^^^\n\n","message":"Data location must be \"memory\" or \"calldata\" for parameter in external function, but none was given.","severity":"error","sourceLocation":{"end":1774,"file":"HealthContract.sol","start":1765},"type":"TypeError"},{"component":"general","errorCode":"6651","formattedMessage":"TypeError: Data location must be \"storage\", \"memory\" or \"calldata\" for variable, but none was given.\n  --> HealthContract.sol:62:3:\n   |\n62 | \t\tstring keyToMove = recordsList[recordsList.length-1];\n   | \t\t^^^^^^^^^^^^^^^^\n\n","message":"Data location must be \"storage\", \"memory\" or \"calldata\" 
for variable, but none was given.","severity":"error","sourceLocation":{"end":1938,"file":"HealthContract.sol","start":1922},"type":"TypeError"}]`

This error generated after calling the deploy() function. So I dived into the contractTemplate.txt file and added the data locations wherever required, and it generated this error

`Error: Solidity compilation error
[{"component":"general","errorCode":"2271","formattedMessage":"TypeError: Operator == not compatible with types string storage ref and string memory.\n  --> HealthContract.sol:23:11:\n   |\n23 | \t\treturn (recordsList[facts[recordAddress].listPointer] == recordAddress);\n   | \t\t        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n\n","message":"Operator == not compatible with types string storage ref and string memory.","severity":"error","sourceLocation":{"end":663,"file":"HealthContract.sol","start":601},"type":"TypeError"}]`

Please resolve this as soon as possible

**Comment by petrosDemetrakopoulos** [comment]
Can you please mention what version of the library you used and the model (in JSON) that you tried to deploy?
This info is absolutely necessary to investigate and resolve the issue.

**Comment by Adarsh-gif-crypt** [comment]
The version is 1.4.7. Nevermind we solved the error. Instead of using `bytes32` for string in the schema in js, we were using `string` directly. That caused the data location errors to pop up. You can close the error now if you do not need any more information.
