### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by fabioselau077** [petrosDemetrakopoulos/ethairballoons#18]
Hello, thanks for this, amazing!

One question, in doc "Note: As transaction fees may be huge, it is strongly advised to only deploy EthAir Balloons models in private Ethereum blockchains or locally using ganache-cli", in case how to create "private Ethereum blockchains"?

For production mode is recommend using private Ethereum blockchains ou ganache-cli?

Thx!

**Comment by petrosDemetrakopoulos** [comment]
Hello @fabioselau077 , thanks for your question and your kind words!
Here is an extensive article explaining how you can create a private Ethereum Blockchain.
https://medium.com/swlh/how-to-set-up-a-private-ethereum-blockchain-c0e74260492c

If you enjoyed Ethairballoons, please do not forget to star the project.
Thanks again,
Petros
